version: "3.8"

services:
  client:
    build:
      context: ./client
    container_name: ktk-client
    restart: always
    ports:
      - "8080:80"
    networks:
      - ktk-net

  server:
    build:
      context: ./server
    container_name: ktk-server
    restart: always
    ports:
      - "3000:3000"  
    networks:
      - ktk-net
    env_file:
      - ./server/.env.production

  nginx:
    image: nginx:alpine
    container_name: ktk-nginx
    restart: always
    ports:
      - "80:80"  # Пробрасываем порт 80 для NGINX
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
    networks:
      - ktk-net

networks:
  ktk-net:
    driver: bridge
