version: '3.3'

services:
  backend:
    build:
      context: ./server
    env_file:
      - ./server/.env.production
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
