version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
