version: '3'
services:
  server:
    image: dashboard-ktk_server
    ports:
      - "3000:3000"
    networks:
      - backend

  client:
    build: .
    ports:
      - "4173:80"  # Убедись, что фронт использует другой порт, как мы обсуждали ранее
    networks:
      - frontend

networks:
  frontend:
  backend:
