version: '3.3'

services:
  frontend:
    build:
      context: .  # Контекст сборки для фронтенда - корень проекта
      dockerfile: client/Dockerfile  # Указываем путь к Dockerfile для фронтенда
    ports:
      - "80:80"
    env_file:
      - server/.env.production
    depends_on:
      - backend

  backend:
    build:
      context: .  # Контекст сборки для бэкенда - корень проекта
      dockerfile: server/Dockerfile  # Указываем путь к Dockerfile для бэкенда
    env_file:
      - server/.env.production
    ports:
      - "3000:3000"
