version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production
    networks:
      - backend

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:80"
    volumes:
      - ./client:/app
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
